apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: ClusterIP
