apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarit-deployment
spec:
  replicas: 6
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 10s
  selector:
    matchLabels:
      app: web-sarit-second
  template:
    metadata:
      labels:
        app: web-sarit-second
    spec:
      containers:
      - name: sarit-second-container
        image: saritnovikg/my-second-app:2.0
        ports:
        - containerPort: 5000
