## example with livenessProbe - check if the pod is alive and restart if not 
##(in this case every 5 seconds)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       —name: nginx
          image: nginx
          ports:
           —containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80 
            initialDelaySeconds: 5 ## initialDelaySeconds - how long to wait before checking
            periodSeconds: 5 ##periodSeconds - how often to checks